# -*- coding: utf-8 -*-
"""GroupProject

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tRvqvNqF0vpMnczoEETAT1yzNp64g_En
"""

# Step 1: We upload 'share-deaths-air-pollution.csv' to the /content directory in Google Colab.

# Step 2: Read the file
import pandas as pd
import plotly.express as px

file_path = 'share-deaths-air-pollution.csv'
data = pd.read_csv(file_path)

# Focus on the year 2019
data_2019 = data[data['Year'] == 2019]

# Create a new column for formatted hover text
data_2019['Share Display'] = data_2019['Share of total deaths that are from all causes attributed to air pollution, in both sexes aged age-standardized'].apply(lambda x: f'{x:.2f}%')

# Step 3: Create the choropleth map
fig = px.choropleth(data_2019, locations='Code',
                    color='Share of total deaths that are from all causes attributed to air pollution, in both sexes aged age-standardized',
                    hover_name='Entity', # Country names
                    hover_data={'Share Display': True}, # Use the new column for hover info
                    projection='natural earth',
                    title='Share of Deaths Attributable to Air Pollution by Country, 2019',
                    color_continuous_scale=px.colors.sequential.OrRd)

# Modifier le layout de la figure pour changer la couleur de fond
fig.update_layout(
    geo=dict(
        bgcolor='lightblue'
    ),
    width=1600, height=900 # Ajuster la taille de la figure
)

# Afficher la figure
fig.show()